config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true, length: { is: 10 }

  def self.search(search)
    if search
      User.where("name LIKE ? OR email LIKE ?","%#{search}%","%#{search}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.search(params[:search])
    @users=User.search(params[:search])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(param_user)
    if @user.save
      redirect_to users_path, notice: "User successfuly created"
    else
      render :new
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(param_user)
      redirect_to users_path,notice: "User successfuly updated"
    else
      render :edit
    end
  end
  def destroy
    @users = User.find(params[:id])
    @users.destroy
    redirect_to users_path,:notice => "User successfuly deleted"
  end
  def show
    @user = User.find(params[:id])
  end
  private
  def param_user
    params.require(:user).permit(:name, :email, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Userapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <% flash.each do |key,value|%>
    <p><%= value %></p>
  <% end %>
  <div class="container">
  <br />
    <%= yield %>
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/users/edit.html.erb
<h1>Update User</h1>
<%= form_for @user do |u| %>
<div>
<%= u.label :name %>
<%= u.text_field :name,required: true,class:"form-control col-md-6" %><br />
</div>
<div>
<%= u.label :Email %>
<%= u.text_field :email,required: true,class:"form-control col-md-6" %><br />
</div>
<div>
<%= u.label :Phone %>
<%= u.text_field :phone,required: true,class:"form-control col-md-6" %>
</div>
<div>
<br />
<%= u.submit %>  
<%= link_to 'Back',users_path,class:'btn btn-dark' %>
</div>
<% end %>

app/views/users/index.html.erb
<h1>All Users List</h1>
<%= form_tag users_path, :method => 'get' do%>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Search",class:'btn btn-info' %>
<% end %>
<br />
 <%= link_to 'Create New',new_user_path,class:'btn btn-primary' %>
<br /><br /><br />
<table class="table table-bordered">
  <thead class="thead-dark">
    <th>Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Operation</th>
  </thead>
  <tbody>
    <% @users.each do |us| %>
    <tr>
      <td><%= us.name %></td>
      <td><%= us.email %></td>
      <td><%= us.phone %></td>
      <td>
      <%= link_to 'View',user_path(us),class:'btn btn-info' %>
      <%= link_to 'Edit',edit_user_path(us),class:'btn btn-primary' %>
    <%= link_to 'Delete',us,method: :delete,data: { confirm:"Ary you sure to delete" },class:'btn btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Add New User</h1>
<%= form_for @user do |u| %>
<div>
<%= u.label :name %>
<%= u.text_field :name,required: true, placeholder: "Enter Your Name",class:"form-control col-md-6" %><br />
</div>
<div>
<%= u.label :Email %>
<%= u.text_field :email,required: true, placeholder: "Enter Your Email",class:"form-control col-md-6" %><br />
</div>
<div>
<%= u.label :Phone %>
<%= u.text_field :phone,required: true, placeholder: "Enter Your Phone",class:"form-control col-md-6" %>
</div>
<br />
<div>
<%= u.submit %>
<%= link_to 'Back',users_path,class:'btn btn-dark' %>
</div>
<br />
<% end %>
<% if @user.errors.any? %>
<%= @user.errors.full_messages %>
<% end %>

app/views/users/show.html.erb
<h1>Details of The User</h1>
<br />
<h3>Name : <%= @user.name %></h3>
<h3>Email : <%= @user.email %></h3>
<h3>Phone Number : <%= @user.phone %></h3>
<%= link_to 'Back',users_path,class:'btn btn-dark' %>